.TH _PRINTF 3 "2025-11-26" "v1.0" "_printf Manual"
.SH NAME
_printf \- Format and print data

.SH SYNOPSIS
._printf(const char *format, ...);

.SH DESCRIPTION

.B _printf
Displays text formatted according to a string passed as an argument. 
It supports certain specifiers such as %c, %s, %d, %i, etc.

.SH RETURN VALUE
Returns the number of characters printed.

.SH EXAMPLES

/* Print value */
_printf("Value : %d\n", 42);
OUTPUT:
Valeur : 42

/* Print Signed value */
_printf("Signed value : %i\n", -98);
OUTPUT:
Valeur signée : -98

/* Print string */
_printf("Nom : %s\n", "Bonjour");
OUTPUT:
Nom : Bonjour

.SH AUTHOR
Théo Caulet
Florian Roosebeke

.SH SEE ALSO
printf(3)
